blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #Index
    path('', views.index, name='index'),

    #Search
    path('products/', views.search, name='search'),

    #All products
    path('products/<slug:type>/<slug:order>/', views.products, name="products"),

    #Product details
    path('products/<int:prod_id>/', views.detail, name='detail'),

    #Cart
    path('сart/', views.cart, name="cart"),

    #Delete
    path('cart/', views.delete, name="del"),

    #Change
    path('change/', views.change, name="change"),

    #Buy
    path('buy/', views.buy, name="buy"),

    #Register
    path('register/',views.UserFormView.as_view(), name='register'),

    #Idea
    path('mail/', views.mail, name='mail'),

    #Admin
    path('adminka/', views.admin, name='admin_cust'),
]

my_cake/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls,name="adminka"),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]


if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

class needforvideo(models.Model):
    title=models.CharField(max_length=50)
    img=models.FileField( blank=True)
    #is_using_now=models.BooleanField(default=False)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name="видео для главной страницы"
        verbose_name_plural="Видео"

class feedback(models.Model):
    author = models.CharField(max_length=50)
    number = models.CharField(max_length=50)
    text = models.TextField()
    def get_absolute_url(self):
        return reverse('index')
    def __str__(self):
        return self.text

    class Meta:
        verbose_name="отзыв"
        verbose_name_plural="Отзывы"

class kolvo(models.Model):
    def __str__(self):
        return self.name
    name=models.CharField(max_length=70)

class Type(models.Model):
    name=models.CharField(max_length=70)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name="группу продуктов"
        verbose_name_plural="Группы продуктов"


class product(models.Model):
    type=models.ForeignKey(Type, on_delete=models.CASCADE)
    title=models.CharField(max_length=70)
    content=models.TextField()
    price=models.IntegerField()
    edinica=models.ForeignKey(kolvo, on_delete=models.CASCADE)
    img=models.FileField( blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name="продукт"
        verbose_name_plural="Продукты"

blog/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import feedback
from django.contrib.auth.forms import UserCreationForm



class UserForm(forms.ModelForm):
    password = forms.CharField( widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']



class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def save(self,commit = True):
        user=super(RegistrationForm, self).save(commit = False)
        user.email=self.cleaned_data['email']
        if commit:
            user.save()
        return user


class FeedbackForm(forms.ModelForm):
    author = forms.CharField( label='',max_length=50 , widget=forms.TextInput(attrs={'class': "feed",'placeholder':"Ваше имя"}))
    number = forms.IntegerField( label='' , widget=forms.NumberInput(attrs={'class': "feed",'placeholder':"Ваш номер телефона"}))
    text = forms.CharField(label='', max_length=141 , widget=forms.Textarea(attrs={'class': "feed",'placeholder':"Ваше впечатление"}))
    class Meta:
        model = feedback
        fields = [ 'author', 'number','text']
    def save(self,commit = True):
        feed=super(FeedbackForm, self).save(commit = False)
        if commit:
            feed.save()
        return feed

blog/views.py
from .cart import Cart
from .models import Type
from .forms import UserForm
from .models import product
from .models import feedback
from .forms import FeedbackForm
from .models import needforvideo
from django.conf import settings
from .forms import RegistrationForm
from django.views.generic import View
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render,get_object_or_404, get_list_or_404,redirect


#Index
def index(request):
    needforvideos=needforvideo.objects.filter(title='my_cake')
    feedbacks=feedback.objects.order_by('-id')
    if request.method == 'POST':
        form=FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
    forma=FeedbackForm()
    popular=product.objects.order_by('price')[:4]
    latest=product.objects.order_by('-created_date')[:4]
    products=product.objects.all()[:4]
    return render(request, 'blog/index.html', {"video":needforvideos,"feedback":feedbacks,'form': forma,"pop":popular,'last':latest,'prods':products})


#Admin
def admin(request):
    return render(request, 'blog/admin.html', {})


#Idea
def mail(request):
    name=request.GET.get('author')
    number=request.GET.get('number')
    idea=request.GET.get('idea')
    msg = render_to_string('mails/idea_mail.html', {'name':name,'number':number,'idea': idea})
    send_mail('Идеи от клиента', msg, settings.EMAIL_HOST_USER ,['qwertyasdfgzxcvpoiu@mail.ru','My_cake_aktau@mail.ru'] )
    needforvideos=needforvideo.objects.filter(title='my_cake')
    feedbacks=feedback.objects.order_by('-id')
    forma=FeedbackForm()
    popular=product.objects.order_by('price')[:4]
    latest=product.objects.order_by('-created_date')[:4]
    products=product.objects.all()[:4]
    return render(request, 'blog/index.html', {"video":needforvideos,"feedback":feedbacks,'form': forma,"pop":popular,'last':latest,'prods':products} )

#All products
def products(request,type,order):
    products=[]
    if type=="tort":
        if order=="chip":
            products=get_list_or_404(product.objects.order_by('price'),type=1)
        else:
            products=get_list_or_404(product.objects.order_by('-price'),type=1)
    elif type=="pirog":
        if order=="chip":
            products=get_list_or_404(product.objects.order_by('price'),type=5)
        else:
            products=get_list_or_404(product.objects.order_by('-price'),type=5)
    elif type=="konfeta":
        if order=="chip":
            products=get_list_or_404(product.objects.order_by('price'),type=3)
        else:
            products=get_list_or_404(product.objects.order_by('-price'),type=3)
    elif type=="desert":
        if order=="chip":
            products=get_list_or_404(product.objects.order_by('price'),type=2)
        else:
            products=get_list_or_404(product.objects.order_by('-price'),type=2)
    elif type=="domash":
        if order=="chip":
            products=get_list_or_404(product.objects.order_by('price'),type=4)
        else:
            products=get_list_or_404(product.objects.order_by('-price'),type=4)
    elif type=="all":
        if order=="chip":
            products=product.objects.order_by('price')
        else:
            products=product.objects.order_by('-price')
    return render(request, 'blog/products.html', {"prods":products, "type":type} )

#Product details
def detail(request,prod_id):
    prod=get_object_or_404(product,id=prod_id)
    return render(request, 'blog/product-detail.html', {"prod":prod, } )

#Cart
def cart(request):
    cart=Cart(request)
    if(request.POST):
        prod_id=request.POST.get('id')
        prod2=get_object_or_404(product,id=prod_id)
        cart.add(prod2)
    sum=cart.get_total_price()
    cart=request.session.get('cart',{})
    return render(request, 'blog/cart.html', {"list":cart,"sum":sum} )


#Delete
def delete(request):
    cart=Cart(request)
    to_del=request.GET.get('delObj')
    prod=get_object_or_404(product,id=to_del)
    cart.remove(prod)
    sum=cart.get_total_price()
    cart=request.session.get('cart',{})
    return render(request, 'blog/cart.html', {"list":cart,"sum":sum,} )


#Change
def change(request):
    cart=Cart(request)
    to_change=request.POST.get('to_change')
    quantity=int(request.POST.get('quantity'))
    prod=product.objects.filter(id=to_change)
    prod=prod[0]
    cart.add(prod,quantity,True)
    sum=cart.get_total_price()
    cart=request.session.get('cart',{})
    return render(request, 'blog/cart.html', {"list":cart,"sum":sum,} )


#Buy
def buy(request):
    cart=Cart(request)
    sum=cart.get_total_price()
    cart=request.session.get('cart',{})
    number=request.GET.get('number')
    if (request.user.is_authenticated):
        name=request.user.username
    else:
        name="Анонимный покупатель"
    msg = render_to_string('mails/Buy_mail.html', {'name':name,'number':number,"list":cart,"sum":sum})
    send_mail('Заказ от клиента', msg, settings.EMAIL_HOST_USER ,['qwertyasdfgzxcvpoiu@mail.ru','My_cake_aktau@mail.ru'] )
    to_clean=Cart(request)
    to_clean.clear()
    return render(request, 'blog/order.html', {"list":cart,"sum":sum} )

#Search
def search(request):
    query=request.GET.get('search')
    if query:
        template='blog/products.html'
        type=Type.objects.filter(name__icontains=query)
        if not type:
            products = product.objects.filter(title__icontains=query)
        else:
            type=type[0]
            products = product.objects.filter(type=type.id)
        context={"prods":products,"type":'all'}
    else:
        template='blog/index.html'
        needforvideos=needforvideo.objects.filter(title='main slider')
        feedbacks=feedback.objects.all()
        forma=FeedbackForm()
        context={"video":needforvideos,"feedback":feedbacks,'form': forma}
    return render(request, template,context )


#Registration
class UserFormView(View):
    form_class=UserForm
    template_name = "registration/register.html"

    #display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})


    #process form data
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            #dont save
            user=form.save(commit=False)

            #cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()#save

            #Returns user object if all ok
            user=authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("index")
        return render(request,self.template_name,{'form':form})

blog/templates/blog/FooterPart.html
{% load staticfiles %}



<!-- footer -->
<footer id="aa-footer">
    <!-- footer bottom -->
    <div class="aa-footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="aa-footer-top-area">
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <div class="aa-footer-widget">
                                    
                                    <ul class="aa-footer-nav">
                                        <li><a href="{% url 'index'%}">Главная</a></li>
                                        <li><a href="{% url 'products' 'tort' 'chip'%}">Торты</a></li>
                                        <li><a href="{% url 'products' 'pirog' 'chip' %}">Пироги</a></li>
                                        <li><a href="{% url 'products' 'konfeta' 'chip' %}">Конфеты</a></li>
                                        <li><a href="{% url 'products' 'desert' 'chip' %}">Десерты</a></li>
                                        <li><a href="{% url 'products' 'domash' 'chip' %}">Домашние изделия</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-6">
                                <div class="aa-footer-widget">
                                    <div class="aa-footer-widget">
                                        
                                        <address>
                                            <!-- for aktau -->
                                            <p><span class="fa fa-location-arrow"></span>
                                                <a href="https://goo.gl/maps/kv1mc3xrBfjziigQ6">Казахстан, г.Актау, 16 мкр, ТРК "АКТАУ"</a>
                                            </p>
                                            <p><span class="fa fa-instagram"></span>
                                                <a href="https://www.instagram.com/my_cake_aktau/">my_cake_aktau</a>
                                            </p>
                                            <p><span class="fa fa-phone"></span>+77058833183</p>
                                             </address>
                                             <address>
                                                
                                            <!-- for zhanaozen -->
                                            <p><span class="fa fa-location-arrow"></span>
                                                <a href="https://goo.gl/maps/1KgKhgFbKHgCLpCe7">Казахстан, г.Жанаозен, 3 мкр, 42 дом</a>
                                            </p>
                                            <p><span class="fa fa-instagram"></span>
                                                <a href="https://www.instagram.com/my_cake_kz/"> my_cake_kz</a>
                                            </p>
                                             <p><span class="fa fa-phone"></span>+77021709661</p>
                                             </address>
                                            
                                       
                                        <address>
                                            <!-- for almaty -->
                                            <p><span class="fa fa-location-arrow"></span>
                                                <a href="https://goo.gl/maps/vuzWtxuoMu5EvWgC9">Казахстан, г.Алматы, ул. Ауезова, 167</a>
                                            </p>
                                            
                                            <p><span class="fa fa-instagram"></span>
                                                <a href="https://www.instagram.com/my_cake_almty/">my_cake_almaty</a>
                                            </p>
                                             <p><span class="fa fa-phone"></span>+77774008199</p>
                                        </address>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom -->

</footer>
<!-- / footer -->

blog/templates/blog/cart.html
{% extends 'blog/wrapper.html' %}
{% load staticfiles %}
{% block content %}


    <div class="container">
        <div class="card shopping-cart">
            <div class="card-header bg-dark text-light">
                <h2 style="padding-top: 90px; margin: 10px"><i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    Корзина</h2>
            </div>
            <div class="card-body">
                {% for key,prod in list.items %}
                <!-- PRODUCT -->
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-2 text-center">
                        <img class="img-responsive" src="{{ prod.img }}" alt="prewiew" width="120" height="80">
                    </div>
                    <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                        <h4 class="product-name"><strong>{{ prod.title }}</strong></h4>
                        <h4>
                            <small>{{ prod.content}}</small>
                        </h4>
                    </div>
                    <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                        <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                            <h6><strong>{{prod.quantity}}{{ prod.ed }} <span class="text-muted">x</span>{{ prod.price }}</strong></h6>
                            <h6><strong>Сумма:{{ prod.sum}}</strong></h6>
                        </div>
                        <div class="col-4 col-sm-4 col-md-4">
                            <div class="quantity">
                                <form action="{% url 'change' %}" method="post" enctype="multipart/form-data" style="border:1px solid; border-radius: 25px; padding-left: 5px;">
                                    {% csrf_token %}
                                    <input type="hidden" name="to_change" value="{{ prod.id }}">
                                    <input type="number" name="quantity" step="1" max="99" min="1" size='2' value="{{ prod.quantity }}" title="Qty" class="qty" style="display: inline; max-width: 30px;border:none;border-radius: 20px;">
                                    <button type="submit" class="btn btn-outline-danger " style="display: inline;background-color: transparent; margin: 0;padding: 0">
                                        <i class="fa fa-check-circle"></i></button>
                                </form>
                            </div>
                        </div>
                        <div class="col-2 col-sm-2 col-md-2 text-right">
                            <form action="{% url 'del'%}" method="get" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="delObj" value="{{ prod.id }}">
                                <button type="submit" class="btn btn-outline-danger " style='background-color: transparent;'>
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
                <hr>
                <!-- END PRODUCT -->
                {% endfor %}
            </div>
            <div class="card-footer">

                {% if list.items %}
                <div class="row">
                    <div class="col-lg-6">
                        <a href="{% url 'products' 'all' 'chip'%}" class="btn btn-block btn-info">Вернуться к покупкам</a>
                    </div>
                    <div class="col-lg-6 pull-right">
                        {% if sum %}
                        <h2>Общая сумма: <b>{{ sum}}тг</b></h2>
                        {% endif %}
                    </div>
                </div>

                <div class="row" style="margin: 15px; margin-top: 20px">
                    <br>
                    <form action="{% url 'buy' %}" class="buy-form" method="get">
                        <div class="row">
                            <p>Пожалуйста введите номер телефона, чтобы наш оператор мог связаться с Вами для уточнения деталей </p>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="number" name="number" class="feed" id="id_number" placeholder="Ваш номер телефона" required >
                            </div>
                            
                            
                            <div class="col-lg-6">
                                <button type="submit" class="btn btn-success btn-block">Заказать</button>
                            </div>
                        </div>
                    </form>
                    <br>
                    <br>
                </div>
                {% else %}
                    <div class="text-danger row">
                        <h3 style="text-align: center"> Ваша корзина пуста</h3>
                    </div>
                    <br>
                    <br>
                    <br>
                    <a href="{% url 'products' 'all' 'chip'%}" class="btn btn-block btn-info"><h4>Вернуться к покупкам</h4></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/order.html
{% extends 'blog/wrapper.html' %}
{% load staticfiles %}
{% block content %}


<div class="container">
    <div class="card shopping-cart">
        <div class="card-header bg-dark text-light">
            <h2 style="padding-top: 90px; margin: 10px"><i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Заказ</h2>
        </div>
        <div class="card-body">
            {{ post }}
            {% for key,prod in list.items %}
            <!-- PRODUCT -->
            <div class="row">
                <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                    <h4 class="product-name"><strong>{{ prod.title }}</strong></h4>
                </div>
                <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                    <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                        <h6><strong>{{prod.quantity}}{{ prod.ed }} <span class="text-muted">x</span>{{ prod.price }}</strong></h6>
                    </div>
                    <div class="col-4 col-sm-4 col-md-4">
                        <h6><strong>{{ prod.sum}}</strong></h6>
                    </div>

                </div>
            </div>
            <hr>
            <!-- END PRODUCT -->
            {% endfor %}
        </div>
        <div class="card-footer">

            <div class="row">
                <div class="text-danger">
                    <h2> {{ error }}</h2>
                </div>
                <div class="pull-right" style="margin: 15px">
                    {% if sum %}
                    <h2>Общая сумма: <b>{{ sum}}тг</b></h2>
                    {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-8">
                    <a href="{% url 'products' 'all' 'chip'%}" class="btn btn-block btn-info">Вернуться к покупкам</a>
                </div>

                <div class="col-lg-2">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/product-detail.html
{% extends 'blog/wrapper.html' %}
{% load staticfiles %}
{% block content %}

    <div class="col-lg-12"id="details-card">
        <div class="col-lg-2">
            <div>
                <button class="btn btn" onClick="javascript:history.go(-1);"><i class="fa fa-arrow-circle-left"></i> Вернуться к списку</button>
            </div>
        </div>
        <div id="details-img" class="col-lg-4">
            <img  src="{{ prod.img.url }}">
        </div>
        <div class="col-lg-4">
            <div id="details-about">
                <h2>{{ prod.title }}</h2>
                {{ prod.content }}
                <br></br>
                
                <p>
                    Цена: <a href="#" id="qv_type">{{ prod.price }} тг/{{ prod.edinica }}</a>
                </p>
            </div>
        </div>
        <div class="col-lg-2"></div>
    </div>
    {% include 'blog/FooterPart.html' %}
{% endblock %}

blog/templates/blog/products.html
{% extends 'blog/wrapper.html' %}
{% load staticfiles %}
{% block content %}

    <section id="aa-popular-category">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="aa-popular-category-area">
                            <ul class="nav nav-tabs aa-products-tab">
                                <li><a href="{% url 'products' 'tort' 'chip'%}">Торты </a></li>
                                <li><img class="uzor" src="{% static 'img/uzor3.png' %}"></li>
                                <li><a href="{% url 'products' 'pirog' 'chip' %}">Пироги </a></li>
                                <li><img class="uzor" src="{% static 'img/uzor3.png' %}"></li>
                                <li><a href="{% url 'products' 'konfeta' 'chip' %}">Конфеты </a></li>
                                <li><img class="uzor" src="{% static 'img/uzor3.png' %}"></li>
                                <li><a href="{% url 'products' 'desert' 'chip' %}">Десерты </a></li>
                                <li><img class="uzor" src="{% static 'img/uzor3.png' %}"></li>
                                <li><a href="{% url 'products' 'domash' 'chip' %}">Домашние изделия </a></li>
                            </ul>
                            <ul class="nav nav-tabs aa-products-tab">
                                <li ><a href="{% url 'products' type 'chip'%}">По возрастанию цены</a></li>
                                <li><img class="uzor" src="{% static 'img/uzor3.png' %}"></li>
                                <li ><a href="{% url 'products' type 'expen'%}">По убыванию цены</a></li>
                            </ul>
                            <!-- Tab panes -->
                            <div class="tab-content">
                                <!-- Start men popular category -->
                                <div class="tab-pane fade in active" id="popular">

                                    <ul class="aa-product-catg" id="chip">
                                        {% if prods %}
                                            {% for prod in prods %}
                                                <!-- start single product item -->
                                                <li>
                                                    <figure>
                                                        <a class="aa-product-img" href="#"><img src="{{ prod.img.url }}" alt="{{ prod.title }}"></a>
                                                        {% if  not request.user.is_staff %}
                                                            <form action="{% url 'cart'%}" method="post">
                                                                {% csrf_token %}
                                                                <input type="hidden" value="{{ prod.id }}" name="id">
                                                                <input type="submit"class="aa-add-card-btn" value="Добавить в корзину" style="width: 100%">
                                                            </form>
                                                        {% endif %}
                                                        <figcaption>
                                                            <h4 class="aa-product-title"><a href="#">{{ prod.title }}</a></h4>
                                                            <span class="aa-product-price">{{ prod.price  }}/{{ prod.edinica }}</span><span class="aa-product-price"></span>
                                                        </figcaption>
                                                    </figure>
                                                    <div class="aa-product-hvr-content">
                                                        
                                                        <a href="{% url 'detail' prod.id%}" ><span class="fa fa-search"> Подробнее</span></a>
                                                    </div>
                                                </li>
                                            {% endfor %}
                                        {% else %}
                                            <div class="container"><br>
                                                <p class="text-danger">сори тут ничего нет</p><br>
                                            </div>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'blog/FooterPart.html' %}
{% endblock %}